name: Pulsar Dependency CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Test 
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-2019]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the Latest Package Code 
        uses: actions/checkout@v3
      - name: Setup Pulsar Editor
        uses: pulsar-edit/action-pulsar-dependency@v2.1
        with:
          package-to-test: "fuzzy-finder"
      - name: Run the Headless Pulsar Tests 
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn start --test spec
          working-directory: ./pulsar
