name: "CI"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-2019]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Install Pulsar
      uses: pulsar-edit/action-pulsar-dependency@v3.2

    - name: Install dependencies (Windows)
      if: ${{ runner.os == 'Windows' }}
      # Currently the Pulsar process starts, but unlike *nix doesn't wait for ppm to finish, probably because pulsar.cmd needs updated
      # So we'll fallback to ppm (still named apm) instead
      run: apm install --verbose

    - name: Install dependencies (*nix)
      if: ${{ runner.os != 'Windows' }}
      run: pulsar --package install --verbose

    - name: Run the headless Pulsar Tests
      uses: coactions/setup-xvfb@v1.0.1
      with:
        run: pulsar --test spec
